

# trust-manager-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trust-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v0.7.0
    path: trust-manager
    helm:
	parameters:
	- name: app.trust.namespace
	value: netbackup-1
  destination:
    server: https://kubernetes.default.svc
    namespace: trust-manager-1
  syncPolicy:
    automated:
	prune: true
	selfHeal: true
